### ISSUE TITLE
Quelldateien und Daten

### ISSUE THREAD

**Issue by stefanw** [netAction/hochschulwatch#1]
Ich sehe gerade, dass das Repo nur aus HTML-Dateien besteht. Ich nehme an, das wird irgendwo automatisch zusammengebaut. Gibt es Zugang die Quelldateien und die Daten? /cc @arnese

**Comment by arnese** [comment]
Ja, Daten sind jetzt alle hier: https://github.com/netAction/hochschulwatch/tree/gh-pages/import
