### ISSUE TITLE
Hochschulnamen aktualisieren

### ISSUE THREAD

**Issue by arnese** [netAction/hochschulwatch#18]
siehe drittmittel.json Spalte "Alternativer Hochschulname"

**Comment by netAction** [comment]
Wofür sind diese Schreibweisen? Ich bin mir nicht sicher, ob die Namen in der blöden Suchfunktion untergebracht werden können.

**Comment by arnese** [comment]
Viele Hochschulnamen haben sich in den letzten Jahren geändert - es wäre eigentlich gut, wenn also sowohl die alten als auch die neuen zum richtigen Ergebnis führen würden. Hm.
