### ISSUE TITLE
Piwik installieren

### ISSUE THREAD

**Issue by arnese** [netAction/hochschulwatch#21]
Wär gut, oder?

**Comment by netAction** [comment]
Piwik eingefügt in 65cad8f

Auf https://piwik.netaction.de Login mit _arnese_

**Comment by Rodlik** [comment]
Ist installiert und läuft (noch?)

**Comment by netAction** [comment]
Ja, Matomo läuft noch, ohne Cookies. Ich habe die Statistik.
