### ISSUE TITLE
Bundesländer als Liste von Hochschulen darstellen und nicht als eigene Seiten

### ISSUE THREAD

**Issue by netAction** [netAction/hochschulwatch#3]
Und Liste der Bundesländer in der Top-Navi auf kleinen Bildschirmen unvollständig.

**Comment by arnese** [comment]
Nö, das geht doch so wie es ist, oder? Aber die Überschrift im Menü sollte "Hochschulen" heißen und nicht "Bundesländer".

**Comment by netAction** [comment]
So etwas meinte ich auch. Gute Idee.

**Comment by arnese** [comment]
OK, dann machen wir das so. Einfach in allen Template-Dateien ändern oder anders?
