### ISSUE TITLE
URLs einfügen

### ISSUE THREAD

**Issue by arnese** [netAction/hochschulwatch#6]
URLs aus Quelldaten als weitere Spalten in den verschiedenen Finanzierungskategorien einbinden

**Comment by netAction** [comment]
Als Spalte? Ich dachte, die werden einfach verlinkt.

**Comment by arnese** [comment]
ha. ja! clever!

**Comment by netAction** [comment]
Ich habe alle verlinkt, nur bei den Stiftungsprofessuren wird die Quelle als Text angezeigt. Ist das so OK?

**Comment by arnese** [comment]
ja, super. dankeschön!
